services:
  app:
    container_name: app
    build:
      context: ./app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.localhost`)"
      - "traefik.http.routers.app.entrypoints=web,websecure"
      # This is not needed, because the container exposes the port 80 itself
      # - "traefik.http.services.app.loadbalancer.server.port=80"

  traefik:
    image: "traefik:latest"
    command:
      - "--api.insecure=true" # Enables Traefik's dashboard via port 8080
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=WARN"
      - "--accesslog=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=web,websecure"

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "http://app:80"
      - "--domain=${NGROK_URL}"
    depends_on:
      - traefik
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
    labels:
      - "traefik.enable=false"
